# Generated by Django 4.2 on 2024-11-26 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否当前生效')),
            ],
        ),
        migrations.CreateModel(
            name='AIRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='AI角色名称')),
                ('prompt', models.TextField(verbose_name='AI角色的提示语')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('context_limit', models.PositiveIntegerField(default=0, verbose_name='历史上下文携带次数')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aimodel', verbose_name='关联模型')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='对话名称')),
                ('dialog_id', models.CharField(max_length=255, unique=True, verbose_name='前端对话ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='对话是否关闭')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
            ],
        ),
        migrations.CreateModel(
            name='DialogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='文本内容')),
                ('message_type', models.CharField(choices=[('user', '用户'), ('ai', 'AI')], max_length=10, verbose_name='消息类型')),
                ('ai_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.airole', verbose_name='AI角色')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.dialog', verbose_name='对话')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='api.user', verbose_name='用户'),
        ),
    ]
