# Generated by Django 4.2 on 2024-11-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
