# Generated by Django 4.2 on 2024-11-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airole',
            name='prompt',
            field=models.TextField(blank=True, null=True, verbose_name='AI角色的提示语'),
        ),
    ]
