# Generated by Django 4.2 on 2024-11-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
    ]
